name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "ef3d24d" --password-stdin
        docker image build -t ef3d24d/gitaction:v1 .
        docker push ef3d24d/gitaction:v1
